# Generated by Django 3.0.4 on 2020-04-17 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200416_1211'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=254)),
                ('describe', models.TextField()),
                ('image', models.CharField(default='', max_length=254)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('editor', models.CharField(default='markdown', max_length=100)),
                ('content_md', models.TextField()),
                ('content_html', models.TextField()),
                ('type', models.SmallIntegerField(default=1)),
                ('commented', models.BooleanField(default=True)),
                ('published', models.BooleanField(default=False)),
                ('draft', models.BooleanField(default=False)),
                ('removed', models.BooleanField(default=False)),
                ('level', models.SmallIntegerField(default=1)),
            ],
            options={
                'db_table': 'blog_article',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='tag',
            name='parent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=254),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Article')),
                ('parent', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'db_table': 'blog_comment',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(related_name='art_tags', to='blog.Tag'),
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
    ]
