# Generated by Django 3.0.4 on 2020-04-17 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200417_1410'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['weight']},
        ),
        migrations.AddField(
            model_name='tag',
            name='weight',
            field=models.SmallIntegerField(default=1),
        ),
    ]
