# Generated by Django 3.0.4 on 2020-04-17 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200417_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='allowed',
        ),
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.SmallIntegerField(default=2),
        ),
    ]
