# Generated by Django 3.0.4 on 2020-04-19 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_tab'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tab',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Tab'),
            preserve_default=False,
        ),
    ]
