# Generated by Django 3.0.4 on 2020-04-19 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_article_tab'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tab',
            options={'ordering': ['index']},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='content_html',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='article',
            name='content_md',
        ),
        migrations.RemoveField(
            model_name='article',
            name='editor',
        ),
    ]
