# Generated by Django 3.0.4 on 2020-04-19 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200419_1101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='published',
            new_name='top',
        ),
    ]
