# Generated by Django 3.0.4 on 2020-04-19 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200419_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='link',
            field=models.CharField(default='', max_length=254),
        ),
    ]
