# Generated by Django 3.0.4 on 2020-04-12 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='auth',
            field=models.CharField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
