# Generated by Django 3.0.4 on 2020-04-12 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_project_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='url_id',
            field=models.CharField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
