# Generated by Django 3.0.4 on 2020-04-12 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_url_url_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='describe',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='url',
            name='describe',
            field=models.CharField(max_length=254),
        ),
    ]
