# Generated by Django 3.0.4 on 2020-04-16 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0005_auto_20200412_1015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='url',
            options={'ordering': ['path']},
        ),
    ]
