# Generated by Django 3.0.4 on 2020-04-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100, unique=True)),
                ('content', models.TextField(default='')),
            ],
            options={
                'db_table': 'setting_index',
            },
        ),
    ]
