# Generated by Django 3.0.4 on 2020-04-01 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jurisdiction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('describe', models.TextField(default='')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('jurisdictions', models.ManyToManyField(related_name='role_jurisdictions', to='jurisdiction.Jurisdiction')),
            ],
            options={
                'db_table': 'person_role',
            },
        ),
    ]
