# Generated by Django 3.0.4 on 2020-04-01 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jurisdiction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=254, unique=True)),
                ('describe', models.TextField(default='')),
                ('identity', models.CharField(max_length=254, unique=True)),
            ],
            options={
                'db_table': 'person_jurisdiction',
                'ordering': ['name'],
            },
        ),
    ]
