# Generated by Django 3.0.4 on 2020-04-01 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200401_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='jurisdiction',
            new_name='jurisdictions',
        ),
    ]
