# Generated by Django 3.0.4 on 2020-04-16 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200416_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='role',
            new_name='roles',
        ),
    ]
