# Generated by Django 3.0.4 on 2020-04-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200416_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='http://ahriknow.oss-cn-beijing.aliyuncs.com/avatar.jpg', max_length=254),
        ),
    ]
