# Generated by Django 3.0.4 on 2020-04-01 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0002_catalog_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='describe',
            field=models.TextField(default=''),
        ),
    ]
