# Generated by Django 3.0.4 on 2020-04-02 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0003_book_describe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='book',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='notebook.Book'),
        ),
    ]
