# Generated by Django 3.0.4 on 2020-04-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0007_auto_20200410_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
